import express from 'express';
import * as productCtrl from '../controllers/product.controller';
import isAuthenticated from '../middlewares/authenticate';
import validate from '../config/joi.validate';
import schema from '../utils/validator';

const router = express.Router();

/**
 * @swagger
 * tags:
 *   - name: product
 *     description: Product operations
 */

/**
 * @swagger
 * definitions:
 *   Product:
 *     type: object
 *     properties:
 *       id:
 *         type: integer
 *         description: Unique identifier representing a specific product
 *         example: 2
 *       title:
 *         type: string
 *         description: title of the product
 *         example: Apple iPhone 12
 *       text:
 *         type: string
 *         description: description of the product
 *         example: Apple iPhone 12 Plus 32GB Factory
 *   Error:
 *     type: object
 *     properties:
 *        message:
 *           type: string
 *        error:
 *           type: boolean
 *           default: true
 */

/**
 * @swagger
 * securityDefinitions:
 *   Bearer:
 *     description: |
 *            For accessing the API a valid JWT token must be passed in all the queries in
 *            the 'Authorization' header.
 *
 *
 *            A valid JWT token is generated by the API and returned as answer of a call
 *            to the route /auth/login giving a valid product & password.
 *
 *
 *            The following syntax must be used in the 'Authorization' header:
 *
 *            Bearer xxxxxx.yyyyyyy.zzzzzz
 *     type: apiKey
 *     name: Authorization
 *     in: header
 *
 */

router.route('/')

/**
 * @swagger
 * /products:
 *   post:
 *     tags:
 *       - product
 *     summary: "Create a new product"
 *     security:
 *        - Bearer: []
 *     operationId: storeProduct
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: body
 *         in: body
 *         description: Created product object
 *         required: true
 *         schema:
 *           $ref: "#/definitions/Product"
 *     responses:
 *       200:
 *         description: OK
 *         schema:
 *           $ref: "#/definitions/Product"
 *       403:
 *          description: Product not found
 *          schema:
 *             $ref: '#/definitions/Error'
 */

    .post(validate(schema.storeProduct), (req, res) => {
        productCtrl.store(req, res);
    })

    /**
     * @swagger
     * /products:
     *   get:
     *     tags:
     *       - product
     *     summary: "List all products"
     *     operationId: findAll
     *     consumes:
     *       - application/json
     *     produces:
     *       - application/json
     *     parameters: []
     *     responses:
     *       200:
     *         description: OK
     *         schema:
     *            type: object
     */

    .get( (req, res) => {
        productCtrl.findAll(req, res);
    });


router.route('/:id')

/**
 * @swagger
 * /products/{id}:
 *   get:
 *     tags:
 *       - product
 *     summary: Find the product by ID
 *     operationId: findById
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: id
 *         in: path
 *         description: id of product that needs to be fetched
 *         required: true
 *         type: integer
 *     responses:
 *       200:
 *         description: OK
 *         schema:
 *           $ref: "#/definitions/Product"
 *       404:
 *          description: Product not found
 *          schema:
 *             $ref: '#/definitions/Error'
 */

    .get( (req, res) => {
        productCtrl.findById(req, res);
    })

    /**
     * @swagger
     * /products/{id}:
     *   put:
     *     tags:
     *       - product
     *     summary: "Update an existing product by ID"
     *     security:
     *       - Bearer: []
     *     operationId: update
     *     consumes:
     *       - application/json
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: id
     *         in: path
     *         description: id that need to be updated
     *         required: true
     *         type: integer
     *       - name: body
     *         in: body
     *         description: Updated product object
     *         required: true
     *         schema:
     *           $ref: "#/definitions/Product"
     *     responses:
     *       200:
     *         description: OK
     *         schema:
     *           $ref: "#/definitions/Product"
     *       400:
     *         description: Invalid product
     */

    .put((req, res) => {
        productCtrl.update(req, res);
    })

    /**
     * @swagger
     * /products/{id}:
     *   delete:
     *     tags:
     *       - product
     *     summary: Delete the product by ID
     *     security:
     *       - Bearer: []
     *     operationId: destroy
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: id
     *         in: path
     *         description: id of product that needs to be deleted
     *         required: true
     *         type: integer
     *     responses:
     *       200:
     *         description: OK
     *       400:
     *          description: "Invalid ID"
     */

    .delete((req, res) => {
        productCtrl.destroy(req, res);
    });


export default router;